# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  setup_and_test:
    steps:
      - checkout
      - run: yarn
      - store_artifacts:
          path: artifact
      - run:
          name: "Notify Artifact"
          command: yarn moxci
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/app
    steps:
      - setup_and_test
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - test